<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Edificio[
<!ELEMENT Edificio (Bloque)>
<!ELEMENT Bloque (Planta)>
    <!ATTLIST Bloque nombre ID #REQUIRED >
    <!ELEMENT Planta (Estancia)>
    <!ATTLIST Planta altura CDATA #REQUIRED >
    <!ELEMENT Estancia (Cuadrante)>
    <!ATTLIST Estancia nombre CDATA #REQUIRED >
    <!ELEMENT Cuadrante (SE,NW)>
    <!ATTLIST Cuadrante id CDATA #REQUIRED >
    <!ELEMENT SE (#X,Y)>
    <!ELEMENT X (#PCDATA)>
	<!ELEMENT Y (#PCDATA)>
	<!ELEMENT NW (#X,Y)>
    <!ELEMENT X (#PCDATA)>
	<!ELEMENT Y (#PCDATA)>
]>


<Edificio>
	<Bloque nombre="A">
		<Planta altura="0"></Planta>
		<Planta altura="1">
			<Estancia nombre="Pasillo 1">
				<Cuadrante id="1">
					<SE>
						<X>3.653846154</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>0.0</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="2">
					<SE>
						<X>7.307692308</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>3.653846154</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="3">
					<SE>
						<X>10.961538462</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>7.307692308</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="4">
					<SE>
						<X>14.615384616</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>10.961538462</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="5">
					<SE>
						<X>18.26923077</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>14.615384616</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="6">
					<SE>
						<X>21.923076924</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>18.26923077</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="7">
					<SE>
						<X>25.576923078</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>21.923076924</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="8">
					<SE>
						<X>29.230769232</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>25.576923078</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="9">
					<SE>
						<X>32.884615386</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>29.230769232</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="10">
					<SE>
						<X>36.53846154</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>32.884615386</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="11">
					<SE>
						<X>40.192307694</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>36.53846154</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="12">
					<SE>
						<X>43.846153848</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>40.192307694</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="13">
					<SE>
						<X>47.500000002</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>43.846153848</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="14">
					<SE>
						<X>51.153846156</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>47.500000002</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="15">
					<SE>
						<X>54.80769231</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>51.153846156</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="16">
					<SE>
						<X>58.461538464</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>54.80769231</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="17">
					<SE>
						<X>62.115384618</X>
						<Y>3.653846154</Y>
					</SE>
					<NW>
						<X>58.461538464</X>
						<Y>0.0</Y>
					</NW>
				</Cuadrante>
			</Estancia>
			<Estancia nombre="Pasillo 2">
				<Cuadrante id="1">
					<SE>
						<X>3.653846154</X>
						<Y>8.003846154</Y>
					</SE>
					<NW>
						<X>0.0</X>
						<Y>3.653846154</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="2">
					<SE>
						<X>3.653846154</X>
						<Y>12.353846154</Y>
					</SE>
					<NW>
						<X>0.0</X>
						<Y>8.003846154</Y>
					</NW>
				</Cuadrante>
			</Estancia>
			<Estancia nombre="Pasillo 3">

				<Cuadrante id="1">
					<SE>
						<X>3.653846154</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>0.0</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="2">
					<SE>
						<X>7.307692308</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>3.653846154</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="3">
					<SE>
						<X>10.961538462</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>7.307692308</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="4">
					<SE>
						<X>14.615384616</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>10.961538462</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="5">
					<SE>
						<X>18.26923077</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>14.615384616</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="6">
					<SE>
						<X>21.923076924</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>18.26923077</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="7">
					<SE>
						<X>25.576923078</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>21.923076924</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="8">
					<SE>
						<X>29.230769232</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>25.576923078</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="9">
					<SE>
						<X>32.884615386</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>29.230769232</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="10">
					<SE>
						<X>36.53846154</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>32.884615386</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="11">
					<SE>
						<X>40.192307694</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>36.53846154</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="12">
					<SE>
						<X>43.846153848</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>40.192307694</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="13">
					<SE>
						<X>47.500000002</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>43.846153848</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="14">
					<SE>
						<X>51.153846156</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>47.500000002</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="15">
					<SE>
						<X>54.80769231</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>51.153846156</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="16">
					<SE>
						<X>58.461538464</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>54.80769231</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="17">
					<SE>
						<X>62.115384618</X>
						<Y>16.153846154</Y>
					</SE>
					<NW>
						<X>58.461538464</X>
						<Y>12.5</Y>
					</NW>
				</Cuadrante>
			</Estancia>
			<Estancia nombre="Pasillo 4">
				<Cuadrante id="1">
					<SE>
						<X>52.00769231</X>
						<Y>8.003846154</Y>
					</SE>
					<NW>
						<X>49.7</X>
						<Y>3.653846154</Y>
					</NW>
				</Cuadrante>
				<Cuadrante id="2">
					<SE>
						<X>52.00769231</X>
						<Y>12.353846154</Y>
					</SE>
					<NW>
						<X>49.7</X>
						<Y>8.003846154</Y>
					</NW>
				</Cuadrante>
			</Estancia>
		</Planta>
		<Planta altura="2"></Planta>
		<Planta altura="3"></Planta>
		<Planta altura="4"></Planta>
	</Bloque>
	<Bloque nombre="B"></Bloque>
</Edificio>